---
title: "California Adjusted Gross Income by ZipCode"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F)
```

Map shows the California average adjusted gross income by zip code.

Data source: [link](https://data.ca.gov/dataset/personal-income-tax-statistics-by-zip-code)

```{r map}
library(leaflet)
library(tidyr)
library(dplyr)
library(stringr)

setwd("C:/Users/Tiffany/Documents/Coursera/Developing Data Products in R")

taxDataRaw <- read.table("Personal_Income_Tax_Statistics_By_Zip_Code.csv",
                      header = T,
                      sep = ",",
                      strip.white = T)

taxDataClean <- taxDataRaw %>%
  select(Returns, CA.AGI, Geo.ZipCode) %>%
  filter(Returns != 0 & CA.AGI != 0 & !is.null(Geo.ZipCode) & Geo.ZipCode != '') %>%
  group_by(Geo.ZipCode) %>%
  summarise(Returns = sum(Returns),
            AGI = sum(CA.AGI)) %>%
  separate(Geo.ZipCode,
           c("a","lng","lat"),
           sep = ' ') %>%
  mutate(avgAGI = AGI/Returns) %>%
  mutate(longitude = as.numeric(str_trim(str_replace(lng,'\\(','')))) %>%
  mutate(latitude = as.numeric(str_trim(str_replace(lat,'\\)','')))) %>%
  select(latitude, longitude, avgAGI)

taxDataClean %>%
  leaflet() %>%
  addTiles() %>%
  addCircleMarkers(lat = ~latitude,
             lng = ~longitude,
             clusterOptions = markerClusterOptions(),
             label = ~as.character(round(avgAGI)))
```

Create date: 1/3/2021